# Generated by Django 5.0.6 on 2024-06-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=100)),
                ('scien_name', models.CharField(max_length=100)),
                ('weigth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wide', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number', models.IntegerField()),
                ('place', models.CharField(choices=[('land', 'Land'), ('sea', 'Sea'), ('forest', 'Forest'), ('lask', 'Lask'), ('mangrove forest', 'Mangrove forest')], default='land', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
